import { CSSResult } from 'lit'

export const bodyDefaultTextClass: CSSResult
export const bodyLargeTextClass: CSSResult
export const bodyMicroTextClass: CSSResult
export const bodySmallTextClass: CSSResult
export const emphasisDefaultTextClass: CSSResult
export const emphasisLargeTextClass: CSSResult
export const emphasisMicroTextClass: CSSResult
export const emphasisSmallTextClass: CSSResult
export const headingLarge3TextClass: CSSResult
export const headingLarge4TextClass: CSSResult
export const headingLarge5TextClass: CSSResult
export const headingLarge6TextClass: CSSResult
export const headingLarge1TextClass: CSSResult
export const headingLarge2TextClass: CSSResult
export const headingSmall1TextClass: CSSResult
export const headingSmall2TextClass: CSSResult
export const headingSmall3TextClass: CSSResult
export const headingSmall4TextClass: CSSResult
export const headingSmall5TextClass: CSSResult
export const headingSmall6TextClass: CSSResult
export const linkLargeTextClass: CSSResult
export const linkMicroTextClass: CSSResult
export const linkSmallTextClass: CSSResult
export const linkDefaultTextClass: CSSResult
export const uiHelperTextClass: CSSResult
export const uiIdTextClass: CSSResult
export const uiLabelTextClass: CSSResult
export const uiPlaceholderTextClass: CSSResult
export const uiTagTextClass: CSSResult
