import { CSSResult } from 'lit'

export module FdsProperty {
  export const Size1: CSSResult
  export const Size2: CSSResult
  export const Size3: CSSResult
  export const Size4: CSSResult
  export const Size6: CSSResult
  export const Size8: CSSResult
  export const Size12: CSSResult
  export const Size16: CSSResult
  export const Size24: CSSResult
  export const Size32: CSSResult
  export const RadiusCompact: CSSResult
  export const RadiusNormal: CSSResult
  export const RadiusLarge: CSSResult
  export const RadiusRounded: CSSResult
  export const StyleElevation100: CSSResult
  export const StyleElevation200: CSSResult
  export const StyleElevation300: CSSResult
  export const StyleElevation400: CSSResult
  export const TypographyBodyDefaultFontFamily: CSSResult
  export const TypographyBodyDefaultFontSize: CSSResult
  export const TypographyBodyDefaultLetterSpacing: CSSResult
  export const TypographyBodyDefaultLineHeight: CSSResult
  export const TypographyBodyDefaultFontWeight: CSSResult
  export const TypographyBodyDefaultDisplay: CSSResult
  export const TypographyBodyLargeFontFamily: CSSResult
  export const TypographyBodyLargeFontSize: CSSResult
  export const TypographyBodyLargeLetterSpacing: CSSResult
  export const TypographyBodyLargeLineHeight: CSSResult
  export const TypographyBodyLargeFontWeight: CSSResult
  export const TypographyBodyLargeDisplay: CSSResult
  export const TypographyBodyMicroFontFamily: CSSResult
  export const TypographyBodyMicroFontSize: CSSResult
  export const TypographyBodyMicroLetterSpacing: CSSResult
  export const TypographyBodyMicroLineHeight: CSSResult
  export const TypographyBodyMicroFontWeight: CSSResult
  export const TypographyBodyMicroDisplay: CSSResult
  export const TypographyBodySmallFontFamily: CSSResult
  export const TypographyBodySmallFontSize: CSSResult
  export const TypographyBodySmallLetterSpacing: CSSResult
  export const TypographyBodySmallLineHeight: CSSResult
  export const TypographyBodySmallFontWeight: CSSResult
  export const TypographyBodySmallDisplay: CSSResult
  export const TypographyEmphasisDefaultFontFamily: CSSResult
  export const TypographyEmphasisDefaultFontSize: CSSResult
  export const TypographyEmphasisDefaultLetterSpacing: CSSResult
  export const TypographyEmphasisDefaultLineHeight: CSSResult
  export const TypographyEmphasisDefaultFontWeight: CSSResult
  export const TypographyEmphasisDefaultDisplay: CSSResult
  export const TypographyEmphasisLargeFontFamily: CSSResult
  export const TypographyEmphasisLargeFontSize: CSSResult
  export const TypographyEmphasisLargeLetterSpacing: CSSResult
  export const TypographyEmphasisLargeLineHeight: CSSResult
  export const TypographyEmphasisLargeFontWeight: CSSResult
  export const TypographyEmphasisLargeDisplay: CSSResult
  export const TypographyEmphasisMicroFontFamily: CSSResult
  export const TypographyEmphasisMicroFontSize: CSSResult
  export const TypographyEmphasisMicroLetterSpacing: CSSResult
  export const TypographyEmphasisMicroLineHeight: CSSResult
  export const TypographyEmphasisMicroFontWeight: CSSResult
  export const TypographyEmphasisMicroDisplay: CSSResult
  export const TypographyEmphasisSmallFontFamily: CSSResult
  export const TypographyEmphasisSmallFontSize: CSSResult
  export const TypographyEmphasisSmallLetterSpacing: CSSResult
  export const TypographyEmphasisSmallLineHeight: CSSResult
  export const TypographyEmphasisSmallFontWeight: CSSResult
  export const TypographyEmphasisSmallDisplay: CSSResult
  export const TypographyHeadingLargeHeading3FontFamily: CSSResult
  export const TypographyHeadingLargeHeading3FontSize: CSSResult
  export const TypographyHeadingLargeHeading3LetterSpacing: CSSResult
  export const TypographyHeadingLargeHeading3LineHeight: CSSResult
  export const TypographyHeadingLargeHeading3FontWeight: CSSResult
  export const TypographyHeadingLargeHeading3Display: CSSResult
  export const TypographyHeadingLargeHeading4FontFamily: CSSResult
  export const TypographyHeadingLargeHeading4FontSize: CSSResult
  export const TypographyHeadingLargeHeading4LetterSpacing: CSSResult
  export const TypographyHeadingLargeHeading4LineHeight: CSSResult
  export const TypographyHeadingLargeHeading4FontWeight: CSSResult
  export const TypographyHeadingLargeHeading4Display: CSSResult
  export const TypographyHeadingLargeHeading5FontFamily: CSSResult
  export const TypographyHeadingLargeHeading5FontSize: CSSResult
  export const TypographyHeadingLargeHeading5LetterSpacing: CSSResult
  export const TypographyHeadingLargeHeading5LineHeight: CSSResult
  export const TypographyHeadingLargeHeading5FontWeight: CSSResult
  export const TypographyHeadingLargeHeading5Display: CSSResult
  export const TypographyHeadingLargeHeading6FontFamily: CSSResult
  export const TypographyHeadingLargeHeading6FontSize: CSSResult
  export const TypographyHeadingLargeHeading6LetterSpacing: CSSResult
  export const TypographyHeadingLargeHeading6LineHeight: CSSResult
  export const TypographyHeadingLargeHeading6FontWeight: CSSResult
  export const TypographyHeadingLargeHeading6Display: CSSResult
  export const TypographyHeadingLargeHeading1FontFamily: CSSResult
  export const TypographyHeadingLargeHeading1FontSize: CSSResult
  export const TypographyHeadingLargeHeading1LetterSpacing: CSSResult
  export const TypographyHeadingLargeHeading1LineHeight: CSSResult
  export const TypographyHeadingLargeHeading1FontWeight: CSSResult
  export const TypographyHeadingLargeHeading1Display: CSSResult
  export const TypographyHeadingLargeHeading2FontFamily: CSSResult
  export const TypographyHeadingLargeHeading2FontSize: CSSResult
  export const TypographyHeadingLargeHeading2LetterSpacing: CSSResult
  export const TypographyHeadingLargeHeading2LineHeight: CSSResult
  export const TypographyHeadingLargeHeading2FontWeight: CSSResult
  export const TypographyHeadingLargeHeading2Display: CSSResult
  export const TypographyHeadingSmallHeading1FontFamily: CSSResult
  export const TypographyHeadingSmallHeading1FontSize: CSSResult
  export const TypographyHeadingSmallHeading1LetterSpacing: CSSResult
  export const TypographyHeadingSmallHeading1LineHeight: CSSResult
  export const TypographyHeadingSmallHeading1FontWeight: CSSResult
  export const TypographyHeadingSmallHeading1Display: CSSResult
  export const TypographyHeadingSmallHeading2FontFamily: CSSResult
  export const TypographyHeadingSmallHeading2FontSize: CSSResult
  export const TypographyHeadingSmallHeading2LetterSpacing: CSSResult
  export const TypographyHeadingSmallHeading2LineHeight: CSSResult
  export const TypographyHeadingSmallHeading2FontWeight: CSSResult
  export const TypographyHeadingSmallHeading2Display: CSSResult
  export const TypographyHeadingSmallHeading3FontFamily: CSSResult
  export const TypographyHeadingSmallHeading3FontSize: CSSResult
  export const TypographyHeadingSmallHeading3LetterSpacing: CSSResult
  export const TypographyHeadingSmallHeading3LineHeight: CSSResult
  export const TypographyHeadingSmallHeading3FontWeight: CSSResult
  export const TypographyHeadingSmallHeading3Display: CSSResult
  export const TypographyHeadingSmallHeading4FontFamily: CSSResult
  export const TypographyHeadingSmallHeading4FontSize: CSSResult
  export const TypographyHeadingSmallHeading4LetterSpacing: CSSResult
  export const TypographyHeadingSmallHeading4LineHeight: CSSResult
  export const TypographyHeadingSmallHeading4FontWeight: CSSResult
  export const TypographyHeadingSmallHeading4Display: CSSResult
  export const TypographyHeadingSmallHeading5FontFamily: CSSResult
  export const TypographyHeadingSmallHeading5FontSize: CSSResult
  export const TypographyHeadingSmallHeading5LetterSpacing: CSSResult
  export const TypographyHeadingSmallHeading5LineHeight: CSSResult
  export const TypographyHeadingSmallHeading5FontWeight: CSSResult
  export const TypographyHeadingSmallHeading5Display: CSSResult
  export const TypographyHeadingSmallHeading6FontFamily: CSSResult
  export const TypographyHeadingSmallHeading6FontSize: CSSResult
  export const TypographyHeadingSmallHeading6LetterSpacing: CSSResult
  export const TypographyHeadingSmallHeading6LineHeight: CSSResult
  export const TypographyHeadingSmallHeading6FontWeight: CSSResult
  export const TypographyHeadingSmallHeading6Display: CSSResult
  export const TypographyLinkLargeFontFamily: CSSResult
  export const TypographyLinkLargeFontSize: CSSResult
  export const TypographyLinkLargeLetterSpacing: CSSResult
  export const TypographyLinkLargeLineHeight: CSSResult
  export const TypographyLinkLargeFontWeight: CSSResult
  export const TypographyLinkLargeTextDecoration: CSSResult
  export const TypographyLinkLargeDisplay: CSSResult
  export const TypographyLinkMicroFontFamily: CSSResult
  export const TypographyLinkMicroFontSize: CSSResult
  export const TypographyLinkMicroLetterSpacing: CSSResult
  export const TypographyLinkMicroLineHeight: CSSResult
  export const TypographyLinkMicroFontWeight: CSSResult
  export const TypographyLinkMicroTextDecoration: CSSResult
  export const TypographyLinkMicroDisplay: CSSResult
  export const TypographyLinkSmallFontFamily: CSSResult
  export const TypographyLinkSmallFontSize: CSSResult
  export const TypographyLinkSmallLetterSpacing: CSSResult
  export const TypographyLinkSmallLineHeight: CSSResult
  export const TypographyLinkSmallFontWeight: CSSResult
  export const TypographyLinkSmallTextDecoration: CSSResult
  export const TypographyLinkSmallDisplay: CSSResult
  export const TypographyLinkDefaultFontFamily: CSSResult
  export const TypographyLinkDefaultFontSize: CSSResult
  export const TypographyLinkDefaultLetterSpacing: CSSResult
  export const TypographyLinkDefaultLineHeight: CSSResult
  export const TypographyLinkDefaultFontWeight: CSSResult
  export const TypographyLinkDefaultTextDecoration: CSSResult
  export const TypographyLinkDefaultDisplay: CSSResult
  export const TypographyUiHelperFontFamily: CSSResult
  export const TypographyUiHelperFontSize: CSSResult
  export const TypographyUiHelperLetterSpacing: CSSResult
  export const TypographyUiHelperLineHeight: CSSResult
  export const TypographyUiHelperFontWeight: CSSResult
  export const TypographyUiHelperDisplay: CSSResult
  export const TypographyUiIdFontFamily: CSSResult
  export const TypographyUiIdFontSize: CSSResult
  export const TypographyUiIdLetterSpacing: CSSResult
  export const TypographyUiIdLineHeight: CSSResult
  export const TypographyUiIdFontWeight: CSSResult
  export const TypographyUiIdDisplay: CSSResult
  export const TypographyUiLabelFontFamily: CSSResult
  export const TypographyUiLabelFontSize: CSSResult
  export const TypographyUiLabelLetterSpacing: CSSResult
  export const TypographyUiLabelLineHeight: CSSResult
  export const TypographyUiLabelFontWeight: CSSResult
  export const TypographyUiLabelDisplay: CSSResult
  export const TypographyUiPlaceholderFontFamily: CSSResult
  export const TypographyUiPlaceholderFontSize: CSSResult
  export const TypographyUiPlaceholderLetterSpacing: CSSResult
  export const TypographyUiPlaceholderLineHeight: CSSResult
  export const TypographyUiPlaceholderFontWeight: CSSResult
  export const TypographyUiPlaceholderDisplay: CSSResult
  export const TypographyUiTagFontFamily: CSSResult
  export const TypographyUiTagFontSize: CSSResult
  export const TypographyUiTagLetterSpacing: CSSResult
  export const TypographyUiTagLineHeight: CSSResult
  export const TypographyUiTagFontWeight: CSSResult
  export const TypographyUiTagDisplay: CSSResult
  export const ColorBrandBlack: CSSResult
  export const ColorBrandWhite: CSSResult
  export const ColorDanger50: CSSResult
  export const ColorDanger100: CSSResult
  export const ColorDanger200: CSSResult
  export const ColorDanger300: CSSResult
  export const ColorDanger400: CSSResult
  export const ColorInteractive50: CSSResult
  export const ColorInteractive100: CSSResult
  export const ColorInteractive200: CSSResult
  export const ColorInteractive300: CSSResult
  export const ColorInteractive400: CSSResult
  export const ColorNeutral50: CSSResult
  export const ColorNeutral100: CSSResult
  export const ColorNeutral200: CSSResult
  export const ColorNeutral300: CSSResult
  export const ColorNeutral400: CSSResult
  export const ColorSuccess50: CSSResult
  export const ColorSuccess100: CSSResult
  export const ColorSuccess200: CSSResult
  export const ColorSuccess300: CSSResult
  export const ColorSuccess400: CSSResult
  export const ColorText1: CSSResult
  export const ColorText300: CSSResult
  export const ColorText600: CSSResult
  export const ColorText1000: CSSResult
  export const ColorWarning50: CSSResult
  export const ColorWarning100: CSSResult
  export const ColorWarning200: CSSResult
  export const ColorWarning300: CSSResult
  export const ColorWarning400: CSSResult
}
