export type FdsToken = { name: "fds-size-1", value: "8px" } | { name: "fds-size-2", value: "16px" } | { name: "fds-size-3", value: "24px" } | { name: "fds-size-4", value: "32px" } | { name: "fds-size-6", value: "48px" } | { name: "fds-size-8", value: "64px" } | { name: "fds-size-12", value: "96px" } | { name: "fds-size-16", value: "128px" } | { name: "fds-size-24", value: "192px" } | { name: "fds-size-32", value: "256px" } | { name: "fds-radius-compact", value: "2px" } | { name: "fds-radius-normal", value: "4px" } | { name: "fds-radius-large", value: "8px" } | { name: "fds-radius-rounded", value: "1000px" } | { name: "fds-style-elevation-100", value: "0px 1px 2px 0px rgba(0, 0, 0, 0.24), 0px 1px 3px 0px rgba(0, 0, 0, 0.12)" } | { name: "fds-style-elevation-200", value: "0px 6px 6px 0px rgba(0, 0, 0, 0.23), 0px 3px 6px 0px rgba(0, 0, 0, 0.16)" } | { name: "fds-style-elevation-300", value: "0px 6px 12px 0px rgba(0, 0, 0, 0.23), 0px 20px 20px 0px rgba(0, 0, 0, 0.19)" } | { name: "fds-style-elevation-400", value: "0px 20px 20px 0px rgba(0, 0, 0, 0.22), 0px 50px 100px 0px rgba(0, 0, 0, 0.25)" } | { name: "fds-typography-body-default-font-family", value: "'Public Sans'" } | { name: "fds-typography-body-default-font-size", value: "16px" } | { name: "fds-typography-body-default-letter-spacing", value: "0px" } | { name: "fds-typography-body-default-line-height", value: "150%" } | { name: "fds-typography-body-default-font-weight", value: "400" } | { name: "fds-typography-body-default-display", value: "inline-block" } | { name: "fds-typography-body-large-font-family", value: "'Public Sans'" } | { name: "fds-typography-body-large-font-size", value: "18px" } | { name: "fds-typography-body-large-letter-spacing", value: "0px" } | { name: "fds-typography-body-large-line-height", value: "150%" } | { name: "fds-typography-body-large-font-weight", value: "400" } | { name: "fds-typography-body-large-display", value: "inline-block" } | { name: "fds-typography-body-micro-font-family", value: "'Public Sans'" } | { name: "fds-typography-body-micro-font-size", value: "12px" } | { name: "fds-typography-body-micro-letter-spacing", value: "0px" } | { name: "fds-typography-body-micro-line-height", value: "150%" } | { name: "fds-typography-body-micro-font-weight", value: "400" } | { name: "fds-typography-body-micro-display", value: "inline-block" } | { name: "fds-typography-body-small-font-family", value: "'Public Sans'" } | { name: "fds-typography-body-small-font-size", value: "14px" } | { name: "fds-typography-body-small-letter-spacing", value: "0px" } | { name: "fds-typography-body-small-line-height", value: "150%" } | { name: "fds-typography-body-small-font-weight", value: "400" } | { name: "fds-typography-body-small-display", value: "inline-block" } | { name: "fds-typography-emphasis-default-font-family", value: "'Public Sans'" } | { name: "fds-typography-emphasis-default-font-size", value: "16px" } | { name: "fds-typography-emphasis-default-letter-spacing", value: "0px" } | { name: "fds-typography-emphasis-default-line-height", value: "150%" } | { name: "fds-typography-emphasis-default-font-weight", value: "700" } | { name: "fds-typography-emphasis-default-display", value: "inline-block" } | { name: "fds-typography-emphasis-large-font-family", value: "'Public Sans'" } | { name: "fds-typography-emphasis-large-font-size", value: "18px" } | { name: "fds-typography-emphasis-large-letter-spacing", value: "0px" } | { name: "fds-typography-emphasis-large-line-height", value: "150%" } | { name: "fds-typography-emphasis-large-font-weight", value: "700" } | { name: "fds-typography-emphasis-large-display", value: "inline-block" } | { name: "fds-typography-emphasis-micro-font-family", value: "'Public Sans'" } | { name: "fds-typography-emphasis-micro-font-size", value: "12px" } | { name: "fds-typography-emphasis-micro-letter-spacing", value: "0px" } | { name: "fds-typography-emphasis-micro-line-height", value: "150%" } | { name: "fds-typography-emphasis-micro-font-weight", value: "700" } | { name: "fds-typography-emphasis-micro-display", value: "inline-block" } | { name: "fds-typography-emphasis-small-font-family", value: "'Public Sans'" } | { name: "fds-typography-emphasis-small-font-size", value: "14px" } | { name: "fds-typography-emphasis-small-letter-spacing", value: "0px" } | { name: "fds-typography-emphasis-small-line-height", value: "150%" } | { name: "fds-typography-emphasis-small-font-weight", value: "700" } | { name: "fds-typography-emphasis-small-display", value: "inline-block" } | { name: "fds-typography-heading-large-heading-3-font-family", value: "'Public Sans', 'PublicSans-Bold'" } | { name: "fds-typography-heading-large-heading-3-font-size", value: "40px" } | { name: "fds-typography-heading-large-heading-3-letter-spacing", value: "0px" } | { name: "fds-typography-heading-large-heading-3-line-height", value: "110%" } | { name: "fds-typography-heading-large-heading-3-font-weight", value: "700" } | { name: "fds-typography-heading-large-heading-3-display", value: "inline-block" } | { name: "fds-typography-heading-large-heading-4-font-family", value: "'Public Sans', 'PublicSans-Bold'" } | { name: "fds-typography-heading-large-heading-4-font-size", value: "32px" } | { name: "fds-typography-heading-large-heading-4-letter-spacing", value: "0px" } | { name: "fds-typography-heading-large-heading-4-line-height", value: "110%" } | { name: "fds-typography-heading-large-heading-4-font-weight", value: "700" } | { name: "fds-typography-heading-large-heading-4-display", value: "inline-block" } | { name: "fds-typography-heading-large-heading-5-font-family", value: "'Public Sans', 'PublicSans-Bold'" } | { name: "fds-typography-heading-large-heading-5-font-size", value: "28px" } | { name: "fds-typography-heading-large-heading-5-letter-spacing", value: "0px" } | { name: "fds-typography-heading-large-heading-5-line-height", value: "110%" } | { name: "fds-typography-heading-large-heading-5-font-weight", value: "700" } | { name: "fds-typography-heading-large-heading-5-display", value: "inline-block" } | { name: "fds-typography-heading-large-heading-6-font-family", value: "'Public Sans', 'PublicSans-Bold'" } | { name: "fds-typography-heading-large-heading-6-font-size", value: "20px" } | { name: "fds-typography-heading-large-heading-6-letter-spacing", value: "0px" } | { name: "fds-typography-heading-large-heading-6-line-height", value: "110%" } | { name: "fds-typography-heading-large-heading-6-font-weight", value: "700" } | { name: "fds-typography-heading-large-heading-6-display", value: "inline-block" } | { name: "fds-typography-heading-large-heading-1-font-family", value: "'Public Sans', 'PublicSans-Bold'" } | { name: "fds-typography-heading-large-heading-1-font-size", value: "64px" } | { name: "fds-typography-heading-large-heading-1-letter-spacing", value: "0px" } | { name: "fds-typography-heading-large-heading-1-line-height", value: "110%" } | { name: "fds-typography-heading-large-heading-1-font-weight", value: "700" } | { name: "fds-typography-heading-large-heading-1-display", value: "inline-block" } | { name: "fds-typography-heading-large-heading-2-font-family", value: "'Public Sans', 'PublicSans-Bold'" } | { name: "fds-typography-heading-large-heading-2-font-size", value: "48px" } | { name: "fds-typography-heading-large-heading-2-letter-spacing", value: "0px" } | { name: "fds-typography-heading-large-heading-2-line-height", value: "110%" } | { name: "fds-typography-heading-large-heading-2-font-weight", value: "700" } | { name: "fds-typography-heading-large-heading-2-display", value: "inline-block" } | { name: "fds-typography-heading-small-heading-1-font-family", value: "'Public Sans', 'PublicSans-Bold'" } | { name: "fds-typography-heading-small-heading-1-font-size", value: "42px" } | { name: "fds-typography-heading-small-heading-1-letter-spacing", value: "0px" } | { name: "fds-typography-heading-small-heading-1-line-height", value: "110%" } | { name: "fds-typography-heading-small-heading-1-font-weight", value: "700" } | { name: "fds-typography-heading-small-heading-1-display", value: "inline-block" } | { name: "fds-typography-heading-small-heading-2-font-family", value: "'Public Sans', 'PublicSans-Bold'" } | { name: "fds-typography-heading-small-heading-2-font-size", value: "32px" } | { name: "fds-typography-heading-small-heading-2-letter-spacing", value: "0px" } | { name: "fds-typography-heading-small-heading-2-line-height", value: "110%" } | { name: "fds-typography-heading-small-heading-2-font-weight", value: "700" } | { name: "fds-typography-heading-small-heading-2-display", value: "inline-block" } | { name: "fds-typography-heading-small-heading-3-font-family", value: "'Public Sans', 'PublicSans-Bold'" } | { name: "fds-typography-heading-small-heading-3-font-size", value: "28px" } | { name: "fds-typography-heading-small-heading-3-letter-spacing", value: "0px" } | { name: "fds-typography-heading-small-heading-3-line-height", value: "110%" } | { name: "fds-typography-heading-small-heading-3-font-weight", value: "700" } | { name: "fds-typography-heading-small-heading-3-display", value: "inline-block" } | { name: "fds-typography-heading-small-heading-4-font-family", value: "'Public Sans', 'PublicSans-Bold'" } | { name: "fds-typography-heading-small-heading-4-font-size", value: "24px" } | { name: "fds-typography-heading-small-heading-4-letter-spacing", value: "0px" } | { name: "fds-typography-heading-small-heading-4-line-height", value: "110%" } | { name: "fds-typography-heading-small-heading-4-font-weight", value: "700" } | { name: "fds-typography-heading-small-heading-4-display", value: "inline-block" } | { name: "fds-typography-heading-small-heading-5-font-family", value: "'Public Sans', 'PublicSans-Bold'" } | { name: "fds-typography-heading-small-heading-5-font-size", value: "18px" } | { name: "fds-typography-heading-small-heading-5-letter-spacing", value: "0px" } | { name: "fds-typography-heading-small-heading-5-line-height", value: "110%" } | { name: "fds-typography-heading-small-heading-5-font-weight", value: "700" } | { name: "fds-typography-heading-small-heading-5-display", value: "inline-block" } | { name: "fds-typography-heading-small-heading-6-font-family", value: "'Public Sans', 'PublicSans-Bold'" } | { name: "fds-typography-heading-small-heading-6-font-size", value: "16px" } | { name: "fds-typography-heading-small-heading-6-letter-spacing", value: "0px" } | { name: "fds-typography-heading-small-heading-6-line-height", value: "110%" } | { name: "fds-typography-heading-small-heading-6-font-weight", value: "700" } | { name: "fds-typography-heading-small-heading-6-display", value: "inline-block" } | { name: "fds-typography-link-large-font-family", value: "'Public Sans'" } | { name: "fds-typography-link-large-font-size", value: "18px" } | { name: "fds-typography-link-large-letter-spacing", value: "0px" } | { name: "fds-typography-link-large-line-height", value: "150%" } | { name: "fds-typography-link-large-font-weight", value: "400" } | { name: "fds-typography-link-large-text-decoration", value: "underline" } | { name: "fds-typography-link-large-display", value: "inline-block" } | { name: "fds-typography-link-micro-font-family", value: "'Public Sans'" } | { name: "fds-typography-link-micro-font-size", value: "12px" } | { name: "fds-typography-link-micro-letter-spacing", value: "0px" } | { name: "fds-typography-link-micro-line-height", value: "150%" } | { name: "fds-typography-link-micro-font-weight", value: "400" } | { name: "fds-typography-link-micro-text-decoration", value: "underline" } | { name: "fds-typography-link-micro-display", value: "inline-block" } | { name: "fds-typography-link-small-font-family", value: "'Public Sans'" } | { name: "fds-typography-link-small-font-size", value: "14px" } | { name: "fds-typography-link-small-letter-spacing", value: "0px" } | { name: "fds-typography-link-small-line-height", value: "150%" } | { name: "fds-typography-link-small-font-weight", value: "400" } | { name: "fds-typography-link-small-text-decoration", value: "underline" } | { name: "fds-typography-link-small-display", value: "inline-block" } | { name: "fds-typography-link-default-font-family", value: "'Public Sans'" } | { name: "fds-typography-link-default-font-size", value: "16px" } | { name: "fds-typography-link-default-letter-spacing", value: "0px" } | { name: "fds-typography-link-default-line-height", value: "150%" } | { name: "fds-typography-link-default-font-weight", value: "400" } | { name: "fds-typography-link-default-text-decoration", value: "underline" } | { name: "fds-typography-link-default-display", value: "inline-block" } | { name: "fds-typography-ui-helper-font-family", value: "'Public Sans', 'PublicSans-Regular'" } | { name: "fds-typography-ui-helper-font-size", value: "15px" } | { name: "fds-typography-ui-helper-letter-spacing", value: "0px" } | { name: "fds-typography-ui-helper-line-height", value: "100%" } | { name: "fds-typography-ui-helper-font-weight", value: "400" } | { name: "fds-typography-ui-helper-display", value: "inline-block" } | { name: "fds-typography-ui-id-font-family", value: "'Roboto Mono'" } | { name: "fds-typography-ui-id-font-size", value: "13px" } | { name: "fds-typography-ui-id-letter-spacing", value: "0px" } | { name: "fds-typography-ui-id-line-height", value: "100%" } | { name: "fds-typography-ui-id-font-weight", value: "700" } | { name: "fds-typography-ui-id-display", value: "inline-block" } | { name: "fds-typography-ui-label-font-family", value: "'Public Sans', 'PublicSans-Medium'" } | { name: "fds-typography-ui-label-font-size", value: "16px" } | { name: "fds-typography-ui-label-letter-spacing", value: "0px" } | { name: "fds-typography-ui-label-line-height", value: "22px" } | { name: "fds-typography-ui-label-font-weight", value: "500" } | { name: "fds-typography-ui-label-display", value: "inline-block" } | { name: "fds-typography-ui-placeholder-font-family", value: "'Public Sans', 'PublicSans-Medium'" } | { name: "fds-typography-ui-placeholder-font-size", value: "16px" } | { name: "fds-typography-ui-placeholder-letter-spacing", value: "0px" } | { name: "fds-typography-ui-placeholder-line-height", value: "100%" } | { name: "fds-typography-ui-placeholder-font-weight", value: "500" } | { name: "fds-typography-ui-placeholder-display", value: "inline-block" } | { name: "fds-typography-ui-tag-font-family", value: "'Public Sans', 'PublicSans-Bold'" } | { name: "fds-typography-ui-tag-font-size", value: "16px" } | { name: "fds-typography-ui-tag-letter-spacing", value: "0px" } | { name: "fds-typography-ui-tag-line-height", value: "100%" } | { name: "fds-typography-ui-tag-font-weight", value: "700" } | { name: "fds-typography-ui-tag-display", value: "inline-block" } | { name: "fds-color-brand-black", value: "#000000" } | { name: "fds-color-brand-white", value: "#ffffff" } | { name: "fds-color-danger-100", value: "#ff9b87" } | { name: "fds-color-danger-200", value: "#e55636" } | { name: "fds-color-danger-300", value: "#b40000" } | { name: "fds-color-danger-400", value: "#720000" } | { name: "fds-color-interactive-100", value: "#90cefe" } | { name: "fds-color-interactive-200", value: "#1777f8" } | { name: "fds-color-interactive-300", value: "#0034ac" } | { name: "fds-color-interactive-400", value: "#001c5b" } | { name: "fds-color-neutral-100", value: "#cdcdd7" } | { name: "fds-color-neutral-200", value: "#9696aa" } | { name: "fds-color-neutral-300", value: "#505064" } | { name: "fds-color-neutral-400", value: "#2c2c44" } | { name: "fds-color-success-100", value: "#82e8c3" } | { name: "fds-color-success-200", value: "#25a794" } | { name: "fds-color-success-300", value: "#005f61" } | { name: "fds-color-success-400", value: "#004042" } | { name: "fds-color-text-1", value: "#ffffff" } | { name: "fds-color-text-300", value: "#9696aa" } | { name: "fds-color-text-600", value: "#505064" } | { name: "fds-color-text-1000", value: "#000000" } | { name: "fds-color-warning-100", value: "#ffe37f" } | { name: "fds-color-warning-200", value: "#eec200" } | { name: "fds-color-warning-300", value: "#b47324" } | { name: "fds-color-warning-400", value: "#6c3e05" }
export type FdsColorToken = { name: "fds-color-brand-black", value: "#000000" } | { name: "fds-color-brand-white", value: "#ffffff" } | { name: "fds-color-danger-100", value: "#ff9b87" } | { name: "fds-color-danger-200", value: "#e55636" } | { name: "fds-color-danger-300", value: "#b40000" } | { name: "fds-color-danger-400", value: "#720000" } | { name: "fds-color-interactive-100", value: "#90cefe" } | { name: "fds-color-interactive-200", value: "#1777f8" } | { name: "fds-color-interactive-300", value: "#0034ac" } | { name: "fds-color-interactive-400", value: "#001c5b" } | { name: "fds-color-neutral-100", value: "#cdcdd7" } | { name: "fds-color-neutral-200", value: "#9696aa" } | { name: "fds-color-neutral-300", value: "#505064" } | { name: "fds-color-neutral-400", value: "#2c2c44" } | { name: "fds-color-success-100", value: "#82e8c3" } | { name: "fds-color-success-200", value: "#25a794" } | { name: "fds-color-success-300", value: "#005f61" } | { name: "fds-color-success-400", value: "#004042" } | { name: "fds-color-text-1", value: "#ffffff" } | { name: "fds-color-text-300", value: "#9696aa" } | { name: "fds-color-text-600", value: "#505064" } | { name: "fds-color-text-1000", value: "#000000" } | { name: "fds-color-warning-100", value: "#ffe37f" } | { name: "fds-color-warning-200", value: "#eec200" } | { name: "fds-color-warning-300", value: "#b47324" } | { name: "fds-color-warning-400", value: "#6c3e05" }
export const FdsSize1: FdsToken
export const FdsSize2: FdsToken
export const FdsSize3: FdsToken
export const FdsSize4: FdsToken
export const FdsSize6: FdsToken
export const FdsSize8: FdsToken
export const FdsSize12: FdsToken
export const FdsSize16: FdsToken
export const FdsSize24: FdsToken
export const FdsSize32: FdsToken
export const FdsRadiusCompact: FdsToken
export const FdsRadiusNormal: FdsToken
export const FdsRadiusLarge: FdsToken
export const FdsRadiusRounded: FdsToken
export const FdsStyleElevation100: FdsToken
export const FdsStyleElevation200: FdsToken
export const FdsStyleElevation300: FdsToken
export const FdsStyleElevation400: FdsToken
export const FdsTypographyBodyDefaultFontFamily: FdsToken
export const FdsTypographyBodyDefaultFontSize: FdsToken
export const FdsTypographyBodyDefaultLetterSpacing: FdsToken
export const FdsTypographyBodyDefaultLineHeight: FdsToken
export const FdsTypographyBodyDefaultFontWeight: FdsToken
export const FdsTypographyBodyDefaultDisplay: FdsToken
export const FdsTypographyBodyLargeFontFamily: FdsToken
export const FdsTypographyBodyLargeFontSize: FdsToken
export const FdsTypographyBodyLargeLetterSpacing: FdsToken
export const FdsTypographyBodyLargeLineHeight: FdsToken
export const FdsTypographyBodyLargeFontWeight: FdsToken
export const FdsTypographyBodyLargeDisplay: FdsToken
export const FdsTypographyBodyMicroFontFamily: FdsToken
export const FdsTypographyBodyMicroFontSize: FdsToken
export const FdsTypographyBodyMicroLetterSpacing: FdsToken
export const FdsTypographyBodyMicroLineHeight: FdsToken
export const FdsTypographyBodyMicroFontWeight: FdsToken
export const FdsTypographyBodyMicroDisplay: FdsToken
export const FdsTypographyBodySmallFontFamily: FdsToken
export const FdsTypographyBodySmallFontSize: FdsToken
export const FdsTypographyBodySmallLetterSpacing: FdsToken
export const FdsTypographyBodySmallLineHeight: FdsToken
export const FdsTypographyBodySmallFontWeight: FdsToken
export const FdsTypographyBodySmallDisplay: FdsToken
export const FdsTypographyEmphasisDefaultFontFamily: FdsToken
export const FdsTypographyEmphasisDefaultFontSize: FdsToken
export const FdsTypographyEmphasisDefaultLetterSpacing: FdsToken
export const FdsTypographyEmphasisDefaultLineHeight: FdsToken
export const FdsTypographyEmphasisDefaultFontWeight: FdsToken
export const FdsTypographyEmphasisDefaultDisplay: FdsToken
export const FdsTypographyEmphasisLargeFontFamily: FdsToken
export const FdsTypographyEmphasisLargeFontSize: FdsToken
export const FdsTypographyEmphasisLargeLetterSpacing: FdsToken
export const FdsTypographyEmphasisLargeLineHeight: FdsToken
export const FdsTypographyEmphasisLargeFontWeight: FdsToken
export const FdsTypographyEmphasisLargeDisplay: FdsToken
export const FdsTypographyEmphasisMicroFontFamily: FdsToken
export const FdsTypographyEmphasisMicroFontSize: FdsToken
export const FdsTypographyEmphasisMicroLetterSpacing: FdsToken
export const FdsTypographyEmphasisMicroLineHeight: FdsToken
export const FdsTypographyEmphasisMicroFontWeight: FdsToken
export const FdsTypographyEmphasisMicroDisplay: FdsToken
export const FdsTypographyEmphasisSmallFontFamily: FdsToken
export const FdsTypographyEmphasisSmallFontSize: FdsToken
export const FdsTypographyEmphasisSmallLetterSpacing: FdsToken
export const FdsTypographyEmphasisSmallLineHeight: FdsToken
export const FdsTypographyEmphasisSmallFontWeight: FdsToken
export const FdsTypographyEmphasisSmallDisplay: FdsToken
export const FdsTypographyHeadingLargeHeading3FontFamily: FdsToken
export const FdsTypographyHeadingLargeHeading3FontSize: FdsToken
export const FdsTypographyHeadingLargeHeading3LetterSpacing: FdsToken
export const FdsTypographyHeadingLargeHeading3LineHeight: FdsToken
export const FdsTypographyHeadingLargeHeading3FontWeight: FdsToken
export const FdsTypographyHeadingLargeHeading3Display: FdsToken
export const FdsTypographyHeadingLargeHeading4FontFamily: FdsToken
export const FdsTypographyHeadingLargeHeading4FontSize: FdsToken
export const FdsTypographyHeadingLargeHeading4LetterSpacing: FdsToken
export const FdsTypographyHeadingLargeHeading4LineHeight: FdsToken
export const FdsTypographyHeadingLargeHeading4FontWeight: FdsToken
export const FdsTypographyHeadingLargeHeading4Display: FdsToken
export const FdsTypographyHeadingLargeHeading5FontFamily: FdsToken
export const FdsTypographyHeadingLargeHeading5FontSize: FdsToken
export const FdsTypographyHeadingLargeHeading5LetterSpacing: FdsToken
export const FdsTypographyHeadingLargeHeading5LineHeight: FdsToken
export const FdsTypographyHeadingLargeHeading5FontWeight: FdsToken
export const FdsTypographyHeadingLargeHeading5Display: FdsToken
export const FdsTypographyHeadingLargeHeading6FontFamily: FdsToken
export const FdsTypographyHeadingLargeHeading6FontSize: FdsToken
export const FdsTypographyHeadingLargeHeading6LetterSpacing: FdsToken
export const FdsTypographyHeadingLargeHeading6LineHeight: FdsToken
export const FdsTypographyHeadingLargeHeading6FontWeight: FdsToken
export const FdsTypographyHeadingLargeHeading6Display: FdsToken
export const FdsTypographyHeadingLargeHeading1FontFamily: FdsToken
export const FdsTypographyHeadingLargeHeading1FontSize: FdsToken
export const FdsTypographyHeadingLargeHeading1LetterSpacing: FdsToken
export const FdsTypographyHeadingLargeHeading1LineHeight: FdsToken
export const FdsTypographyHeadingLargeHeading1FontWeight: FdsToken
export const FdsTypographyHeadingLargeHeading1Display: FdsToken
export const FdsTypographyHeadingLargeHeading2FontFamily: FdsToken
export const FdsTypographyHeadingLargeHeading2FontSize: FdsToken
export const FdsTypographyHeadingLargeHeading2LetterSpacing: FdsToken
export const FdsTypographyHeadingLargeHeading2LineHeight: FdsToken
export const FdsTypographyHeadingLargeHeading2FontWeight: FdsToken
export const FdsTypographyHeadingLargeHeading2Display: FdsToken
export const FdsTypographyHeadingSmallHeading1FontFamily: FdsToken
export const FdsTypographyHeadingSmallHeading1FontSize: FdsToken
export const FdsTypographyHeadingSmallHeading1LetterSpacing: FdsToken
export const FdsTypographyHeadingSmallHeading1LineHeight: FdsToken
export const FdsTypographyHeadingSmallHeading1FontWeight: FdsToken
export const FdsTypographyHeadingSmallHeading1Display: FdsToken
export const FdsTypographyHeadingSmallHeading2FontFamily: FdsToken
export const FdsTypographyHeadingSmallHeading2FontSize: FdsToken
export const FdsTypographyHeadingSmallHeading2LetterSpacing: FdsToken
export const FdsTypographyHeadingSmallHeading2LineHeight: FdsToken
export const FdsTypographyHeadingSmallHeading2FontWeight: FdsToken
export const FdsTypographyHeadingSmallHeading2Display: FdsToken
export const FdsTypographyHeadingSmallHeading3FontFamily: FdsToken
export const FdsTypographyHeadingSmallHeading3FontSize: FdsToken
export const FdsTypographyHeadingSmallHeading3LetterSpacing: FdsToken
export const FdsTypographyHeadingSmallHeading3LineHeight: FdsToken
export const FdsTypographyHeadingSmallHeading3FontWeight: FdsToken
export const FdsTypographyHeadingSmallHeading3Display: FdsToken
export const FdsTypographyHeadingSmallHeading4FontFamily: FdsToken
export const FdsTypographyHeadingSmallHeading4FontSize: FdsToken
export const FdsTypographyHeadingSmallHeading4LetterSpacing: FdsToken
export const FdsTypographyHeadingSmallHeading4LineHeight: FdsToken
export const FdsTypographyHeadingSmallHeading4FontWeight: FdsToken
export const FdsTypographyHeadingSmallHeading4Display: FdsToken
export const FdsTypographyHeadingSmallHeading5FontFamily: FdsToken
export const FdsTypographyHeadingSmallHeading5FontSize: FdsToken
export const FdsTypographyHeadingSmallHeading5LetterSpacing: FdsToken
export const FdsTypographyHeadingSmallHeading5LineHeight: FdsToken
export const FdsTypographyHeadingSmallHeading5FontWeight: FdsToken
export const FdsTypographyHeadingSmallHeading5Display: FdsToken
export const FdsTypographyHeadingSmallHeading6FontFamily: FdsToken
export const FdsTypographyHeadingSmallHeading6FontSize: FdsToken
export const FdsTypographyHeadingSmallHeading6LetterSpacing: FdsToken
export const FdsTypographyHeadingSmallHeading6LineHeight: FdsToken
export const FdsTypographyHeadingSmallHeading6FontWeight: FdsToken
export const FdsTypographyHeadingSmallHeading6Display: FdsToken
export const FdsTypographyLinkLargeFontFamily: FdsToken
export const FdsTypographyLinkLargeFontSize: FdsToken
export const FdsTypographyLinkLargeLetterSpacing: FdsToken
export const FdsTypographyLinkLargeLineHeight: FdsToken
export const FdsTypographyLinkLargeFontWeight: FdsToken
export const FdsTypographyLinkLargeTextDecoration: FdsToken
export const FdsTypographyLinkLargeDisplay: FdsToken
export const FdsTypographyLinkMicroFontFamily: FdsToken
export const FdsTypographyLinkMicroFontSize: FdsToken
export const FdsTypographyLinkMicroLetterSpacing: FdsToken
export const FdsTypographyLinkMicroLineHeight: FdsToken
export const FdsTypographyLinkMicroFontWeight: FdsToken
export const FdsTypographyLinkMicroTextDecoration: FdsToken
export const FdsTypographyLinkMicroDisplay: FdsToken
export const FdsTypographyLinkSmallFontFamily: FdsToken
export const FdsTypographyLinkSmallFontSize: FdsToken
export const FdsTypographyLinkSmallLetterSpacing: FdsToken
export const FdsTypographyLinkSmallLineHeight: FdsToken
export const FdsTypographyLinkSmallFontWeight: FdsToken
export const FdsTypographyLinkSmallTextDecoration: FdsToken
export const FdsTypographyLinkSmallDisplay: FdsToken
export const FdsTypographyLinkDefaultFontFamily: FdsToken
export const FdsTypographyLinkDefaultFontSize: FdsToken
export const FdsTypographyLinkDefaultLetterSpacing: FdsToken
export const FdsTypographyLinkDefaultLineHeight: FdsToken
export const FdsTypographyLinkDefaultFontWeight: FdsToken
export const FdsTypographyLinkDefaultTextDecoration: FdsToken
export const FdsTypographyLinkDefaultDisplay: FdsToken
export const FdsTypographyUiHelperFontFamily: FdsToken
export const FdsTypographyUiHelperFontSize: FdsToken
export const FdsTypographyUiHelperLetterSpacing: FdsToken
export const FdsTypographyUiHelperLineHeight: FdsToken
export const FdsTypographyUiHelperFontWeight: FdsToken
export const FdsTypographyUiHelperDisplay: FdsToken
export const FdsTypographyUiIdFontFamily: FdsToken
export const FdsTypographyUiIdFontSize: FdsToken
export const FdsTypographyUiIdLetterSpacing: FdsToken
export const FdsTypographyUiIdLineHeight: FdsToken
export const FdsTypographyUiIdFontWeight: FdsToken
export const FdsTypographyUiIdDisplay: FdsToken
export const FdsTypographyUiLabelFontFamily: FdsToken
export const FdsTypographyUiLabelFontSize: FdsToken
export const FdsTypographyUiLabelLetterSpacing: FdsToken
export const FdsTypographyUiLabelLineHeight: FdsToken
export const FdsTypographyUiLabelFontWeight: FdsToken
export const FdsTypographyUiLabelDisplay: FdsToken
export const FdsTypographyUiPlaceholderFontFamily: FdsToken
export const FdsTypographyUiPlaceholderFontSize: FdsToken
export const FdsTypographyUiPlaceholderLetterSpacing: FdsToken
export const FdsTypographyUiPlaceholderLineHeight: FdsToken
export const FdsTypographyUiPlaceholderFontWeight: FdsToken
export const FdsTypographyUiPlaceholderDisplay: FdsToken
export const FdsTypographyUiTagFontFamily: FdsToken
export const FdsTypographyUiTagFontSize: FdsToken
export const FdsTypographyUiTagLetterSpacing: FdsToken
export const FdsTypographyUiTagLineHeight: FdsToken
export const FdsTypographyUiTagFontWeight: FdsToken
export const FdsTypographyUiTagDisplay: FdsToken
export const FdsColorBrandBlack: FdsColorToken
export const FdsColorBrandWhite: FdsColorToken
export const FdsColorDanger100: FdsColorToken
export const FdsColorDanger200: FdsColorToken
export const FdsColorDanger300: FdsColorToken
export const FdsColorDanger400: FdsColorToken
export const FdsColorInteractive100: FdsColorToken
export const FdsColorInteractive200: FdsColorToken
export const FdsColorInteractive300: FdsColorToken
export const FdsColorInteractive400: FdsColorToken
export const FdsColorNeutral100: FdsColorToken
export const FdsColorNeutral200: FdsColorToken
export const FdsColorNeutral300: FdsColorToken
export const FdsColorNeutral400: FdsColorToken
export const FdsColorSuccess100: FdsColorToken
export const FdsColorSuccess200: FdsColorToken
export const FdsColorSuccess300: FdsColorToken
export const FdsColorSuccess400: FdsColorToken
export const FdsColorText1: FdsColorToken
export const FdsColorText300: FdsColorToken
export const FdsColorText600: FdsColorToken
export const FdsColorText1000: FdsColorToken
export const FdsColorWarning100: FdsColorToken
export const FdsColorWarning200: FdsColorToken
export const FdsColorWarning300: FdsColorToken
export const FdsColorWarning400: FdsColorToken