export const FdsSize1 = { name: "fds-size-1", value: "8px" }
export const FdsSize2 = { name: "fds-size-2", value: "16px" }
export const FdsSize3 = { name: "fds-size-3", value: "24px" }
export const FdsSize4 = { name: "fds-size-4", value: "32px" }
export const FdsSize6 = { name: "fds-size-6", value: "48px" }
export const FdsSize8 = { name: "fds-size-8", value: "64px" }
export const FdsSize12 = { name: "fds-size-12", value: "96px" }
export const FdsSize16 = { name: "fds-size-16", value: "128px" }
export const FdsSize24 = { name: "fds-size-24", value: "192px" }
export const FdsSize32 = { name: "fds-size-32", value: "256px" }
export const FdsRadiusCompact = { name: "fds-radius-compact", value: "2px" }
export const FdsRadiusNormal = { name: "fds-radius-normal", value: "4px" }
export const FdsRadiusLarge = { name: "fds-radius-large", value: "8px" }
export const FdsRadiusRounded = { name: "fds-radius-rounded", value: "1000px" }
export const FdsStyleElevation100 = { name: "fds-style-elevation-100", value: "0px 1px 2px 0px rgba(0, 0, 0, 0.24), 0px 1px 3px 0px rgba(0, 0, 0, 0.12)" }
export const FdsStyleElevation200 = { name: "fds-style-elevation-200", value: "0px 6px 6px 0px rgba(0, 0, 0, 0.23), 0px 3px 6px 0px rgba(0, 0, 0, 0.16)" }
export const FdsStyleElevation300 = { name: "fds-style-elevation-300", value: "0px 6px 12px 0px rgba(0, 0, 0, 0.23), 0px 20px 20px 0px rgba(0, 0, 0, 0.19)" }
export const FdsStyleElevation400 = { name: "fds-style-elevation-400", value: "0px 20px 20px 0px rgba(0, 0, 0, 0.22), 0px 50px 100px 0px rgba(0, 0, 0, 0.25)" }
export const FdsTypographyBodyDefaultFontFamily = { name: "fds-typography-body-default-font-family", value: "'Public Sans'" }
export const FdsTypographyBodyDefaultFontSize = { name: "fds-typography-body-default-font-size", value: "16px" }
export const FdsTypographyBodyDefaultLetterSpacing = { name: "fds-typography-body-default-letter-spacing", value: "0px" }
export const FdsTypographyBodyDefaultLineHeight = { name: "fds-typography-body-default-line-height", value: "150%" }
export const FdsTypographyBodyDefaultFontWeight = { name: "fds-typography-body-default-font-weight", value: "400" }
export const FdsTypographyBodyDefaultDisplay = { name: "fds-typography-body-default-display", value: "inline-block" }
export const FdsTypographyBodyLargeFontFamily = { name: "fds-typography-body-large-font-family", value: "'Public Sans'" }
export const FdsTypographyBodyLargeFontSize = { name: "fds-typography-body-large-font-size", value: "18px" }
export const FdsTypographyBodyLargeLetterSpacing = { name: "fds-typography-body-large-letter-spacing", value: "0px" }
export const FdsTypographyBodyLargeLineHeight = { name: "fds-typography-body-large-line-height", value: "150%" }
export const FdsTypographyBodyLargeFontWeight = { name: "fds-typography-body-large-font-weight", value: "400" }
export const FdsTypographyBodyLargeDisplay = { name: "fds-typography-body-large-display", value: "inline-block" }
export const FdsTypographyBodyMicroFontFamily = { name: "fds-typography-body-micro-font-family", value: "'Public Sans'" }
export const FdsTypographyBodyMicroFontSize = { name: "fds-typography-body-micro-font-size", value: "12px" }
export const FdsTypographyBodyMicroLetterSpacing = { name: "fds-typography-body-micro-letter-spacing", value: "0px" }
export const FdsTypographyBodyMicroLineHeight = { name: "fds-typography-body-micro-line-height", value: "150%" }
export const FdsTypographyBodyMicroFontWeight = { name: "fds-typography-body-micro-font-weight", value: "400" }
export const FdsTypographyBodyMicroDisplay = { name: "fds-typography-body-micro-display", value: "inline-block" }
export const FdsTypographyBodySmallFontFamily = { name: "fds-typography-body-small-font-family", value: "'Public Sans'" }
export const FdsTypographyBodySmallFontSize = { name: "fds-typography-body-small-font-size", value: "14px" }
export const FdsTypographyBodySmallLetterSpacing = { name: "fds-typography-body-small-letter-spacing", value: "0px" }
export const FdsTypographyBodySmallLineHeight = { name: "fds-typography-body-small-line-height", value: "150%" }
export const FdsTypographyBodySmallFontWeight = { name: "fds-typography-body-small-font-weight", value: "400" }
export const FdsTypographyBodySmallDisplay = { name: "fds-typography-body-small-display", value: "inline-block" }
export const FdsTypographyEmphasisDefaultFontFamily = { name: "fds-typography-emphasis-default-font-family", value: "'Public Sans'" }
export const FdsTypographyEmphasisDefaultFontSize = { name: "fds-typography-emphasis-default-font-size", value: "16px" }
export const FdsTypographyEmphasisDefaultLetterSpacing = { name: "fds-typography-emphasis-default-letter-spacing", value: "0px" }
export const FdsTypographyEmphasisDefaultLineHeight = { name: "fds-typography-emphasis-default-line-height", value: "150%" }
export const FdsTypographyEmphasisDefaultFontWeight = { name: "fds-typography-emphasis-default-font-weight", value: "700" }
export const FdsTypographyEmphasisDefaultDisplay = { name: "fds-typography-emphasis-default-display", value: "inline-block" }
export const FdsTypographyEmphasisLargeFontFamily = { name: "fds-typography-emphasis-large-font-family", value: "'Public Sans'" }
export const FdsTypographyEmphasisLargeFontSize = { name: "fds-typography-emphasis-large-font-size", value: "18px" }
export const FdsTypographyEmphasisLargeLetterSpacing = { name: "fds-typography-emphasis-large-letter-spacing", value: "0px" }
export const FdsTypographyEmphasisLargeLineHeight = { name: "fds-typography-emphasis-large-line-height", value: "150%" }
export const FdsTypographyEmphasisLargeFontWeight = { name: "fds-typography-emphasis-large-font-weight", value: "700" }
export const FdsTypographyEmphasisLargeDisplay = { name: "fds-typography-emphasis-large-display", value: "inline-block" }
export const FdsTypographyEmphasisMicroFontFamily = { name: "fds-typography-emphasis-micro-font-family", value: "'Public Sans'" }
export const FdsTypographyEmphasisMicroFontSize = { name: "fds-typography-emphasis-micro-font-size", value: "12px" }
export const FdsTypographyEmphasisMicroLetterSpacing = { name: "fds-typography-emphasis-micro-letter-spacing", value: "0px" }
export const FdsTypographyEmphasisMicroLineHeight = { name: "fds-typography-emphasis-micro-line-height", value: "150%" }
export const FdsTypographyEmphasisMicroFontWeight = { name: "fds-typography-emphasis-micro-font-weight", value: "700" }
export const FdsTypographyEmphasisMicroDisplay = { name: "fds-typography-emphasis-micro-display", value: "inline-block" }
export const FdsTypographyEmphasisSmallFontFamily = { name: "fds-typography-emphasis-small-font-family", value: "'Public Sans'" }
export const FdsTypographyEmphasisSmallFontSize = { name: "fds-typography-emphasis-small-font-size", value: "14px" }
export const FdsTypographyEmphasisSmallLetterSpacing = { name: "fds-typography-emphasis-small-letter-spacing", value: "0px" }
export const FdsTypographyEmphasisSmallLineHeight = { name: "fds-typography-emphasis-small-line-height", value: "150%" }
export const FdsTypographyEmphasisSmallFontWeight = { name: "fds-typography-emphasis-small-font-weight", value: "700" }
export const FdsTypographyEmphasisSmallDisplay = { name: "fds-typography-emphasis-small-display", value: "inline-block" }
export const FdsTypographyHeadingLargeHeading3FontFamily = { name: "fds-typography-heading-large-heading-3-font-family", value: "'Public Sans', 'PublicSans-Bold'" }
export const FdsTypographyHeadingLargeHeading3FontSize = { name: "fds-typography-heading-large-heading-3-font-size", value: "40px" }
export const FdsTypographyHeadingLargeHeading3LetterSpacing = { name: "fds-typography-heading-large-heading-3-letter-spacing", value: "0px" }
export const FdsTypographyHeadingLargeHeading3LineHeight = { name: "fds-typography-heading-large-heading-3-line-height", value: "110%" }
export const FdsTypographyHeadingLargeHeading3FontWeight = { name: "fds-typography-heading-large-heading-3-font-weight", value: "700" }
export const FdsTypographyHeadingLargeHeading3Display = { name: "fds-typography-heading-large-heading-3-display", value: "inline-block" }
export const FdsTypographyHeadingLargeHeading4FontFamily = { name: "fds-typography-heading-large-heading-4-font-family", value: "'Public Sans', 'PublicSans-Bold'" }
export const FdsTypographyHeadingLargeHeading4FontSize = { name: "fds-typography-heading-large-heading-4-font-size", value: "32px" }
export const FdsTypographyHeadingLargeHeading4LetterSpacing = { name: "fds-typography-heading-large-heading-4-letter-spacing", value: "0px" }
export const FdsTypographyHeadingLargeHeading4LineHeight = { name: "fds-typography-heading-large-heading-4-line-height", value: "110%" }
export const FdsTypographyHeadingLargeHeading4FontWeight = { name: "fds-typography-heading-large-heading-4-font-weight", value: "700" }
export const FdsTypographyHeadingLargeHeading4Display = { name: "fds-typography-heading-large-heading-4-display", value: "inline-block" }
export const FdsTypographyHeadingLargeHeading5FontFamily = { name: "fds-typography-heading-large-heading-5-font-family", value: "'Public Sans', 'PublicSans-Bold'" }
export const FdsTypographyHeadingLargeHeading5FontSize = { name: "fds-typography-heading-large-heading-5-font-size", value: "28px" }
export const FdsTypographyHeadingLargeHeading5LetterSpacing = { name: "fds-typography-heading-large-heading-5-letter-spacing", value: "0px" }
export const FdsTypographyHeadingLargeHeading5LineHeight = { name: "fds-typography-heading-large-heading-5-line-height", value: "110%" }
export const FdsTypographyHeadingLargeHeading5FontWeight = { name: "fds-typography-heading-large-heading-5-font-weight", value: "700" }
export const FdsTypographyHeadingLargeHeading5Display = { name: "fds-typography-heading-large-heading-5-display", value: "inline-block" }
export const FdsTypographyHeadingLargeHeading6FontFamily = { name: "fds-typography-heading-large-heading-6-font-family", value: "'Public Sans', 'PublicSans-Bold'" }
export const FdsTypographyHeadingLargeHeading6FontSize = { name: "fds-typography-heading-large-heading-6-font-size", value: "20px" }
export const FdsTypographyHeadingLargeHeading6LetterSpacing = { name: "fds-typography-heading-large-heading-6-letter-spacing", value: "0px" }
export const FdsTypographyHeadingLargeHeading6LineHeight = { name: "fds-typography-heading-large-heading-6-line-height", value: "110%" }
export const FdsTypographyHeadingLargeHeading6FontWeight = { name: "fds-typography-heading-large-heading-6-font-weight", value: "700" }
export const FdsTypographyHeadingLargeHeading6Display = { name: "fds-typography-heading-large-heading-6-display", value: "inline-block" }
export const FdsTypographyHeadingLargeHeading1FontFamily = { name: "fds-typography-heading-large-heading-1-font-family", value: "'Public Sans', 'PublicSans-Bold'" }
export const FdsTypographyHeadingLargeHeading1FontSize = { name: "fds-typography-heading-large-heading-1-font-size", value: "64px" }
export const FdsTypographyHeadingLargeHeading1LetterSpacing = { name: "fds-typography-heading-large-heading-1-letter-spacing", value: "0px" }
export const FdsTypographyHeadingLargeHeading1LineHeight = { name: "fds-typography-heading-large-heading-1-line-height", value: "110%" }
export const FdsTypographyHeadingLargeHeading1FontWeight = { name: "fds-typography-heading-large-heading-1-font-weight", value: "700" }
export const FdsTypographyHeadingLargeHeading1Display = { name: "fds-typography-heading-large-heading-1-display", value: "inline-block" }
export const FdsTypographyHeadingLargeHeading2FontFamily = { name: "fds-typography-heading-large-heading-2-font-family", value: "'Public Sans', 'PublicSans-Bold'" }
export const FdsTypographyHeadingLargeHeading2FontSize = { name: "fds-typography-heading-large-heading-2-font-size", value: "48px" }
export const FdsTypographyHeadingLargeHeading2LetterSpacing = { name: "fds-typography-heading-large-heading-2-letter-spacing", value: "0px" }
export const FdsTypographyHeadingLargeHeading2LineHeight = { name: "fds-typography-heading-large-heading-2-line-height", value: "110%" }
export const FdsTypographyHeadingLargeHeading2FontWeight = { name: "fds-typography-heading-large-heading-2-font-weight", value: "700" }
export const FdsTypographyHeadingLargeHeading2Display = { name: "fds-typography-heading-large-heading-2-display", value: "inline-block" }
export const FdsTypographyHeadingSmallHeading1FontFamily = { name: "fds-typography-heading-small-heading-1-font-family", value: "'Public Sans', 'PublicSans-Bold'" }
export const FdsTypographyHeadingSmallHeading1FontSize = { name: "fds-typography-heading-small-heading-1-font-size", value: "42px" }
export const FdsTypographyHeadingSmallHeading1LetterSpacing = { name: "fds-typography-heading-small-heading-1-letter-spacing", value: "0px" }
export const FdsTypographyHeadingSmallHeading1LineHeight = { name: "fds-typography-heading-small-heading-1-line-height", value: "110%" }
export const FdsTypographyHeadingSmallHeading1FontWeight = { name: "fds-typography-heading-small-heading-1-font-weight", value: "700" }
export const FdsTypographyHeadingSmallHeading1Display = { name: "fds-typography-heading-small-heading-1-display", value: "inline-block" }
export const FdsTypographyHeadingSmallHeading2FontFamily = { name: "fds-typography-heading-small-heading-2-font-family", value: "'Public Sans', 'PublicSans-Bold'" }
export const FdsTypographyHeadingSmallHeading2FontSize = { name: "fds-typography-heading-small-heading-2-font-size", value: "32px" }
export const FdsTypographyHeadingSmallHeading2LetterSpacing = { name: "fds-typography-heading-small-heading-2-letter-spacing", value: "0px" }
export const FdsTypographyHeadingSmallHeading2LineHeight = { name: "fds-typography-heading-small-heading-2-line-height", value: "110%" }
export const FdsTypographyHeadingSmallHeading2FontWeight = { name: "fds-typography-heading-small-heading-2-font-weight", value: "700" }
export const FdsTypographyHeadingSmallHeading2Display = { name: "fds-typography-heading-small-heading-2-display", value: "inline-block" }
export const FdsTypographyHeadingSmallHeading3FontFamily = { name: "fds-typography-heading-small-heading-3-font-family", value: "'Public Sans', 'PublicSans-Bold'" }
export const FdsTypographyHeadingSmallHeading3FontSize = { name: "fds-typography-heading-small-heading-3-font-size", value: "28px" }
export const FdsTypographyHeadingSmallHeading3LetterSpacing = { name: "fds-typography-heading-small-heading-3-letter-spacing", value: "0px" }
export const FdsTypographyHeadingSmallHeading3LineHeight = { name: "fds-typography-heading-small-heading-3-line-height", value: "110%" }
export const FdsTypographyHeadingSmallHeading3FontWeight = { name: "fds-typography-heading-small-heading-3-font-weight", value: "700" }
export const FdsTypographyHeadingSmallHeading3Display = { name: "fds-typography-heading-small-heading-3-display", value: "inline-block" }
export const FdsTypographyHeadingSmallHeading4FontFamily = { name: "fds-typography-heading-small-heading-4-font-family", value: "'Public Sans', 'PublicSans-Bold'" }
export const FdsTypographyHeadingSmallHeading4FontSize = { name: "fds-typography-heading-small-heading-4-font-size", value: "24px" }
export const FdsTypographyHeadingSmallHeading4LetterSpacing = { name: "fds-typography-heading-small-heading-4-letter-spacing", value: "0px" }
export const FdsTypographyHeadingSmallHeading4LineHeight = { name: "fds-typography-heading-small-heading-4-line-height", value: "110%" }
export const FdsTypographyHeadingSmallHeading4FontWeight = { name: "fds-typography-heading-small-heading-4-font-weight", value: "700" }
export const FdsTypographyHeadingSmallHeading4Display = { name: "fds-typography-heading-small-heading-4-display", value: "inline-block" }
export const FdsTypographyHeadingSmallHeading5FontFamily = { name: "fds-typography-heading-small-heading-5-font-family", value: "'Public Sans', 'PublicSans-Bold'" }
export const FdsTypographyHeadingSmallHeading5FontSize = { name: "fds-typography-heading-small-heading-5-font-size", value: "18px" }
export const FdsTypographyHeadingSmallHeading5LetterSpacing = { name: "fds-typography-heading-small-heading-5-letter-spacing", value: "0px" }
export const FdsTypographyHeadingSmallHeading5LineHeight = { name: "fds-typography-heading-small-heading-5-line-height", value: "110%" }
export const FdsTypographyHeadingSmallHeading5FontWeight = { name: "fds-typography-heading-small-heading-5-font-weight", value: "700" }
export const FdsTypographyHeadingSmallHeading5Display = { name: "fds-typography-heading-small-heading-5-display", value: "inline-block" }
export const FdsTypographyHeadingSmallHeading6FontFamily = { name: "fds-typography-heading-small-heading-6-font-family", value: "'Public Sans', 'PublicSans-Bold'" }
export const FdsTypographyHeadingSmallHeading6FontSize = { name: "fds-typography-heading-small-heading-6-font-size", value: "16px" }
export const FdsTypographyHeadingSmallHeading6LetterSpacing = { name: "fds-typography-heading-small-heading-6-letter-spacing", value: "0px" }
export const FdsTypographyHeadingSmallHeading6LineHeight = { name: "fds-typography-heading-small-heading-6-line-height", value: "110%" }
export const FdsTypographyHeadingSmallHeading6FontWeight = { name: "fds-typography-heading-small-heading-6-font-weight", value: "700" }
export const FdsTypographyHeadingSmallHeading6Display = { name: "fds-typography-heading-small-heading-6-display", value: "inline-block" }
export const FdsTypographyLinkLargeFontFamily = { name: "fds-typography-link-large-font-family", value: "'Public Sans'" }
export const FdsTypographyLinkLargeFontSize = { name: "fds-typography-link-large-font-size", value: "18px" }
export const FdsTypographyLinkLargeLetterSpacing = { name: "fds-typography-link-large-letter-spacing", value: "0px" }
export const FdsTypographyLinkLargeLineHeight = { name: "fds-typography-link-large-line-height", value: "150%" }
export const FdsTypographyLinkLargeFontWeight = { name: "fds-typography-link-large-font-weight", value: "400" }
export const FdsTypographyLinkLargeTextDecoration = { name: "fds-typography-link-large-text-decoration", value: "underline" }
export const FdsTypographyLinkLargeDisplay = { name: "fds-typography-link-large-display", value: "inline-block" }
export const FdsTypographyLinkMicroFontFamily = { name: "fds-typography-link-micro-font-family", value: "'Public Sans'" }
export const FdsTypographyLinkMicroFontSize = { name: "fds-typography-link-micro-font-size", value: "12px" }
export const FdsTypographyLinkMicroLetterSpacing = { name: "fds-typography-link-micro-letter-spacing", value: "0px" }
export const FdsTypographyLinkMicroLineHeight = { name: "fds-typography-link-micro-line-height", value: "150%" }
export const FdsTypographyLinkMicroFontWeight = { name: "fds-typography-link-micro-font-weight", value: "400" }
export const FdsTypographyLinkMicroTextDecoration = { name: "fds-typography-link-micro-text-decoration", value: "underline" }
export const FdsTypographyLinkMicroDisplay = { name: "fds-typography-link-micro-display", value: "inline-block" }
export const FdsTypographyLinkSmallFontFamily = { name: "fds-typography-link-small-font-family", value: "'Public Sans'" }
export const FdsTypographyLinkSmallFontSize = { name: "fds-typography-link-small-font-size", value: "14px" }
export const FdsTypographyLinkSmallLetterSpacing = { name: "fds-typography-link-small-letter-spacing", value: "0px" }
export const FdsTypographyLinkSmallLineHeight = { name: "fds-typography-link-small-line-height", value: "150%" }
export const FdsTypographyLinkSmallFontWeight = { name: "fds-typography-link-small-font-weight", value: "400" }
export const FdsTypographyLinkSmallTextDecoration = { name: "fds-typography-link-small-text-decoration", value: "underline" }
export const FdsTypographyLinkSmallDisplay = { name: "fds-typography-link-small-display", value: "inline-block" }
export const FdsTypographyLinkDefaultFontFamily = { name: "fds-typography-link-default-font-family", value: "'Public Sans'" }
export const FdsTypographyLinkDefaultFontSize = { name: "fds-typography-link-default-font-size", value: "16px" }
export const FdsTypographyLinkDefaultLetterSpacing = { name: "fds-typography-link-default-letter-spacing", value: "0px" }
export const FdsTypographyLinkDefaultLineHeight = { name: "fds-typography-link-default-line-height", value: "150%" }
export const FdsTypographyLinkDefaultFontWeight = { name: "fds-typography-link-default-font-weight", value: "400" }
export const FdsTypographyLinkDefaultTextDecoration = { name: "fds-typography-link-default-text-decoration", value: "underline" }
export const FdsTypographyLinkDefaultDisplay = { name: "fds-typography-link-default-display", value: "inline-block" }
export const FdsTypographyUiHelperFontFamily = { name: "fds-typography-ui-helper-font-family", value: "'Public Sans', 'PublicSans-Regular'" }
export const FdsTypographyUiHelperFontSize = { name: "fds-typography-ui-helper-font-size", value: "15px" }
export const FdsTypographyUiHelperLetterSpacing = { name: "fds-typography-ui-helper-letter-spacing", value: "0px" }
export const FdsTypographyUiHelperLineHeight = { name: "fds-typography-ui-helper-line-height", value: "100%" }
export const FdsTypographyUiHelperFontWeight = { name: "fds-typography-ui-helper-font-weight", value: "400" }
export const FdsTypographyUiHelperDisplay = { name: "fds-typography-ui-helper-display", value: "inline-block" }
export const FdsTypographyUiIdFontFamily = { name: "fds-typography-ui-id-font-family", value: "'Roboto Mono'" }
export const FdsTypographyUiIdFontSize = { name: "fds-typography-ui-id-font-size", value: "13px" }
export const FdsTypographyUiIdLetterSpacing = { name: "fds-typography-ui-id-letter-spacing", value: "0px" }
export const FdsTypographyUiIdLineHeight = { name: "fds-typography-ui-id-line-height", value: "100%" }
export const FdsTypographyUiIdFontWeight = { name: "fds-typography-ui-id-font-weight", value: "700" }
export const FdsTypographyUiIdDisplay = { name: "fds-typography-ui-id-display", value: "inline-block" }
export const FdsTypographyUiLabelFontFamily = { name: "fds-typography-ui-label-font-family", value: "'Public Sans', 'PublicSans-Medium'" }
export const FdsTypographyUiLabelFontSize = { name: "fds-typography-ui-label-font-size", value: "16px" }
export const FdsTypographyUiLabelLetterSpacing = { name: "fds-typography-ui-label-letter-spacing", value: "0px" }
export const FdsTypographyUiLabelLineHeight = { name: "fds-typography-ui-label-line-height", value: "22px" }
export const FdsTypographyUiLabelFontWeight = { name: "fds-typography-ui-label-font-weight", value: "500" }
export const FdsTypographyUiLabelDisplay = { name: "fds-typography-ui-label-display", value: "inline-block" }
export const FdsTypographyUiPlaceholderFontFamily = { name: "fds-typography-ui-placeholder-font-family", value: "'Public Sans', 'PublicSans-Medium'" }
export const FdsTypographyUiPlaceholderFontSize = { name: "fds-typography-ui-placeholder-font-size", value: "16px" }
export const FdsTypographyUiPlaceholderLetterSpacing = { name: "fds-typography-ui-placeholder-letter-spacing", value: "0px" }
export const FdsTypographyUiPlaceholderLineHeight = { name: "fds-typography-ui-placeholder-line-height", value: "100%" }
export const FdsTypographyUiPlaceholderFontWeight = { name: "fds-typography-ui-placeholder-font-weight", value: "500" }
export const FdsTypographyUiPlaceholderDisplay = { name: "fds-typography-ui-placeholder-display", value: "inline-block" }
export const FdsTypographyUiTagFontFamily = { name: "fds-typography-ui-tag-font-family", value: "'Public Sans', 'PublicSans-Bold'" }
export const FdsTypographyUiTagFontSize = { name: "fds-typography-ui-tag-font-size", value: "16px" }
export const FdsTypographyUiTagLetterSpacing = { name: "fds-typography-ui-tag-letter-spacing", value: "0px" }
export const FdsTypographyUiTagLineHeight = { name: "fds-typography-ui-tag-line-height", value: "100%" }
export const FdsTypographyUiTagFontWeight = { name: "fds-typography-ui-tag-font-weight", value: "700" }
export const FdsTypographyUiTagDisplay = { name: "fds-typography-ui-tag-display", value: "inline-block" }
export const FdsColorBrandBlack = { name: "fds-color-brand-black", value: "#000000" }
export const FdsColorBrandWhite = { name: "fds-color-brand-white", value: "#ffffff" }
export const FdsColorDanger50 = { name: "fds-color-danger-50", value: "#FFF0ED" }
export const FdsColorDanger100 = { name: "fds-color-danger-100", value: "#ff9b87" }
export const FdsColorDanger200 = { name: "fds-color-danger-200", value: "#e55636" }
export const FdsColorDanger300 = { name: "fds-color-danger-300", value: "#b40000" }
export const FdsColorDanger400 = { name: "fds-color-danger-400", value: "#720000" }
export const FdsColorInteractive50 = { name: "fds-color-interactive-50", value: "#EFF8FF" }
export const FdsColorInteractive100 = { name: "fds-color-interactive-100", value: "#90cefe" }
export const FdsColorInteractive200 = { name: "fds-color-interactive-200", value: "#1777f8" }
export const FdsColorInteractive300 = { name: "fds-color-interactive-300", value: "#0034ac" }
export const FdsColorInteractive400 = { name: "fds-color-interactive-400", value: "#001c5b" }
export const FdsColorNeutral50 = { name: "fds-color-neutral-50", value: "#F6F6F6" }
export const FdsColorNeutral100 = { name: "fds-color-neutral-100", value: "#cdcdd7" }
export const FdsColorNeutral200 = { name: "fds-color-neutral-200", value: "#9696aa" }
export const FdsColorNeutral300 = { name: "fds-color-neutral-300", value: "#505064" }
export const FdsColorNeutral400 = { name: "fds-color-neutral-400", value: "#2c2c44" }
export const FdsColorSuccess50 = { name: "fds-color-success-50", value: "#EAFFF8" }
export const FdsColorSuccess100 = { name: "fds-color-success-100", value: "#82e8c3" }
export const FdsColorSuccess200 = { name: "fds-color-success-200", value: "#25a794" }
export const FdsColorSuccess300 = { name: "fds-color-success-300", value: "#005f61" }
export const FdsColorSuccess400 = { name: "fds-color-success-400", value: "#004042" }
export const FdsColorText1 = { name: "fds-color-text-1", value: "#ffffff" }
export const FdsColorText300 = { name: "fds-color-text-300", value: "#9696aa" }
export const FdsColorText600 = { name: "fds-color-text-600", value: "#505064" }
export const FdsColorText1000 = { name: "fds-color-text-1000", value: "#000000" }
export const FdsColorWarning50 = { name: "fds-color-warning-50", value: "#FFFADB" }
export const FdsColorWarning100 = { name: "fds-color-warning-100", value: "#ffe37f" }
export const FdsColorWarning200 = { name: "fds-color-warning-200", value: "#eec200" }
export const FdsColorWarning300 = { name: "fds-color-warning-300", value: "#b47324" }
export const FdsColorWarning400 = { name: "fds-color-warning-400", value: "#6c3e05" }